### ISSUE TITLE
自己编译错误

### ISSUE THREAD

**Issue by seacoastboy** [uniqush/uniqush-push#49] opened 2014-08-15 03:24 UTC
configparser.go:21:2: cannot find package "code.google.com/p/goconf/conf" in any of:
这个库好像在google上面没有了, github上面有几个config库， 应该可以取代吧

**Comment by TysonAndre** [comment] 2017-09-29 04:02
Duplicate of https://github.com/uniqush/uniqush-push/issues/115

New releases use github.com/ifwe/goconf/conf

**Closed by TysonAndre** 2017-09-29 04:02 UTC
Labels: bug, duplicate
