### ISSUE TITLE
Uniqush-push loses APNS connection after 2 hours of inactivity

### ISSUE THREAD

**Issue by szgeri** [uniqush/uniqush-push#68] opened 2015-07-08 14:49 UTC
After exactly 2 hours after being inactive, the connection is closed by APNS and Uniqush-push is unable to reconnect the next time I want to send a message. What happens at this point varies:

1.) I get a "Connection closed by APNS: EOF" in the log. No CURL error, CURL hangs indefinitely.

2.) I get "Connection closed by APNS: read tcp 17.110.226.98:2195: use of closed network connection" in the log. CURL hangs.

3.) CURL says "curl: (52) Empty reply from server" and right after me trying again it says "curl: (7) couldn't connect to host"

4.) It dies and dumps things on the terminal from which it was launched:

[2015-07-08 13:24:20.717909899 +0200 CEST][workder-1436348308-5577006791947779410] I was told to stop (res == nil)
panic: send on closed channel
        panic: close of closed channel

goroutine 106 [running]:
github.com/uniqush/uniqush-push/srv.resultCollector(0x0, 0xc2080caa80, 0x7fc83cb61950, 0xc2080f9600)
        /usr/local/go/src/github.com/uniqush/uniqush-push/srv/apns.go:831
...
and it goes on like this but line#831 (resChan <- res) is where the error occurs.

**Comment by monnand** [comment] 2015-07-10 17:35
Sorry for my late reply. I am currently working on my thesis, preparing for my family visit, and packing/moving my stuff from coast to coast. Well, a busy summer.

I took a brief view of the code. Yes, this is a bug and thanks for your report.

This bug is introduced in 87c7c911daff87e1693a019da02c247177d84ffb by @or-else. In short, you can fix this by removing line 812.

@or-else, Channel resChan passed to function resultCollector() is actually self.resultChan, see line 448. Closing this channel will affect other goroutines reading from/writing to this channel since it is shared between goroutines. I checked the code again, I think the memory leak bug is actually caused by un-closed req.resChan. If I'm correct, then it means you will have lots of goroutines waiting in function waitResults() because the channel resChan passed to this function is never closed.

However, I'm currently not able to make further analysis until mid August. I'm actually considering to rewrite apns.go someday.

**Comment by brejoc** [comment] 2016-11-16 10:45
Has the fix already been released? I'm still seeing `Connection closed by APNS: EOF` in the logs together with no push notifications being sent.

**Comment by TysonAndre** [comment] 2017-09-29 03:42
The fix for the originally reported issue was fixed over a year ago, and hasn't showed up again in the latest releases, so I'm closing this.

As for @brejoc 's issue: Seeing `Connection closed by APNS: EOF` is most frequently caused by not using the proper combination of sandbox endpoint (use sandbox=1 when creating the PSP in uniqush), sandbox certificate, and sandbox iOS app build. (or the proper combination of production endpoint, production certificate, and device token from production iOS app build). It may also be caused by an expired certificate, I think.

- https://github.com/uniqush/uniqush-push/issues/72#issuecomment-169481259
- https://github.com/uniqush/uniqush-push/issues/178#issuecomment-324966156

**Closed by TysonAndre** 2017-09-29 03:42 UTC
Labels: bug
