### ISSUE TITLE
Unique-push

### ISSUE THREAD

**Issue by Sarfo** [uniqush/uniqush-push#243] opened 2019-03-21 22:05 UTC
why does it take too long to start

**Comment by mishan** [comment] 2019-03-21 22:15
@Sarfo Can you give us any more information about your setup? What are you running it on? Can you provide an example of it taking long to start?

**Comment by Sarfo** [comment] 2019-03-26 03:44
Thank you for your response
Im running it on Amazon EC2 Ubuntu free tie

**Comment by mishan** [comment] 2019-03-26 15:37
Can you paste some terminal output? Show us how you run it and illustrate that it takes a while?

This is the first I've heard of this happening -- it starts pretty much instantly from my experience.

Other things to look at -- can the EC2 instance reach Redis instance or is it hanging trying to open that socket?

Without some more info like terminal output and such, I can't do much with this issue.

**Comment by mishan** [comment] 2019-04-02 23:28
@Sarfo Any update? We haven't seen this sort of issue and we run uniqush-push on production at a pretty large scale. We haven't had any other reports of this either.

I'm going to close this issue in a couple of days if I don't hear anything more.

**Comment by mishan** [comment] 2019-06-04 23:57
Closing after 2 months of zero response. Cannot reproduce issue. If you have more details to provide, you may reopen the issue.

Thanks.

**Closed by mishan** 2019-06-04 23:57 UTC
Labels: triage
